/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ReportAnalysisRouteImport } from './routes/report-analysis'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DiseaseDetectionRouteImport } from './routes/disease-detection'
import { Route as AiHealthAssistantRouteImport } from './routes/ai-health-assistant'
import { Route as IndexRouteImport } from './routes/index'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportAnalysisRoute = ReportAnalysisRouteImport.update({
  id: '/report-analysis',
  path: '/report-analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DiseaseDetectionRoute = DiseaseDetectionRouteImport.update({
  id: '/disease-detection',
  path: '/disease-detection',
  getParentRoute: () => rootRouteImport,
} as any)
const AiHealthAssistantRoute = AiHealthAssistantRouteImport.update({
  id: '/ai-health-assistant',
  path: '/ai-health-assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-health-assistant': typeof AiHealthAssistantRoute
  '/disease-detection': typeof DiseaseDetectionRoute
  '/login': typeof LoginRoute
  '/report-analysis': typeof ReportAnalysisRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-health-assistant': typeof AiHealthAssistantRoute
  '/disease-detection': typeof DiseaseDetectionRoute
  '/login': typeof LoginRoute
  '/report-analysis': typeof ReportAnalysisRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-health-assistant': typeof AiHealthAssistantRoute
  '/disease-detection': typeof DiseaseDetectionRoute
  '/login': typeof LoginRoute
  '/report-analysis': typeof ReportAnalysisRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-health-assistant'
    | '/disease-detection'
    | '/login'
    | '/report-analysis'
    | '/signup'
    | '/verify-email'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-health-assistant'
    | '/disease-detection'
    | '/login'
    | '/report-analysis'
    | '/signup'
    | '/verify-email'
  id:
    | '__root__'
    | '/'
    | '/ai-health-assistant'
    | '/disease-detection'
    | '/login'
    | '/report-analysis'
    | '/signup'
    | '/verify-email'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiHealthAssistantRoute: typeof AiHealthAssistantRoute
  DiseaseDetectionRoute: typeof DiseaseDetectionRoute
  LoginRoute: typeof LoginRoute
  ReportAnalysisRoute: typeof ReportAnalysisRoute
  SignupRoute: typeof SignupRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report-analysis': {
      id: '/report-analysis'
      path: '/report-analysis'
      fullPath: '/report-analysis'
      preLoaderRoute: typeof ReportAnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disease-detection': {
      id: '/disease-detection'
      path: '/disease-detection'
      fullPath: '/disease-detection'
      preLoaderRoute: typeof DiseaseDetectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-health-assistant': {
      id: '/ai-health-assistant'
      path: '/ai-health-assistant'
      fullPath: '/ai-health-assistant'
      preLoaderRoute: typeof AiHealthAssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiHealthAssistantRoute: AiHealthAssistantRoute,
  DiseaseDetectionRoute: DiseaseDetectionRoute,
  LoginRoute: LoginRoute,
  ReportAnalysisRoute: ReportAnalysisRoute,
  SignupRoute: SignupRoute,
  VerifyEmailRoute: VerifyEmailRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
